using KUKULCAN.SharedKernel.Validations;

namespace KUKULCAN.SharedKernel.UnitTests.Validations;

/// <summary>
/// Contains unit tests for <see cref="ValidationFailure"/>.
/// </summary>
[TestFixture]
public sealed class ValidationFailureTests
{
    /// <summary>
    /// Verifies that a validation failure can be created with all
    /// explicitly supplied values.
    /// </summary>
    [Test]
    public void Constructor_WithAllValues_ShouldCreateExpectedFailure()
    {
        const string propertyName = "Name";
        const string errorCode = "required";
        const string message = "Name is required.";
        const string attemptedValue = "";

        var failure = new ValidationFailure(
            propertyName,
            errorCode,
            message,
            attemptedValue,
            ValidationSeverity.Error);

        Assert.Multiple(() =>
        {
            Assert.That(failure.PropertyName, Is.EqualTo(propertyName));
            Assert.That(failure.ErrorCode, Is.EqualTo(errorCode));
            Assert.That(failure.Message, Is.EqualTo(message));
            Assert.That(failure.AttemptedValue, Is.EqualTo(attemptedValue));
            Assert.That(
                failure.Severity,
                Is.EqualTo(ValidationSeverity.Error));
        });
    }

    /// <summary>
    /// Verifies that <see cref="ValidationFailure.AttemptedValue"/>
    /// defaults to <see langword="null"/>.
    /// </summary>
    [Test]
    public void Constructor_WithoutAttemptedValue_ShouldSetNullAttemptedValue()
    {
        var failure = new ValidationFailure(
            "Name",
            "required",
            "Name is required.");

        Assert.That(failure.AttemptedValue, Is.Null);
    }

    /// <summary>
    /// Verifies that the default severity is
    /// <see cref="ValidationSeverity.Error"/>.
    /// </summary>
    [Test]
    public void Constructor_WithoutSeverity_ShouldUseErrorSeverity()
    {
        var failure = new ValidationFailure(
            "Name",
            "required",
            "Name is required.");

        Assert.That(
            failure.Severity,
            Is.EqualTo(ValidationSeverity.Error));
    }

    /// <summary>
    /// Verifies that informational severity is preserved.
    /// </summary>
    [Test]
    public void Constructor_WithInformationSeverity_ShouldPreserveSeverity()
    {
        var failure = new ValidationFailure(
            "Name",
            "info",
            "Name contains additional information.",
            "John",
            ValidationSeverity.Information);

        Assert.That(
            failure.Severity,
            Is.EqualTo(ValidationSeverity.Information));
    }

    /// <summary>
    /// Verifies that warning severity is preserved.
    /// </summary>
    [Test]
    public void Constructor_WithWarningSeverity_ShouldPreserveSeverity()
    {
        var failure = new ValidationFailure(
            "Name",
            "warning",
            "Name should be reviewed.",
            "John",
            ValidationSeverity.Warning);

        Assert.That(
            failure.Severity,
            Is.EqualTo(ValidationSeverity.Warning));
    }

    /// <summary>
    /// Verifies that error severity is preserved.
    /// </summary>
    [Test]
    public void Constructor_WithErrorSeverity_ShouldPreserveSeverity()
    {
        var failure = new ValidationFailure(
            "Name",
            "required",
            "Name is required.",
            null,
            ValidationSeverity.Error);

        Assert.That(
            failure.Severity,
            Is.EqualTo(ValidationSeverity.Error));
    }

    /// <summary>
    /// Verifies that a null attempted value is accepted.
    /// </summary>
    [Test]
    public void Constructor_WithNullAttemptedValue_ShouldAcceptNull()
    {
        var failure = new ValidationFailure(
            "Name",
            "required",
            "Name is required.",
            null);

        Assert.That(failure.AttemptedValue, Is.Null);
    }

    /// <summary>
    /// Verifies that a complex attempted value is preserved without
    /// modification.
    /// </summary>
    [Test]
    public void Constructor_WithComplexAttemptedValue_ShouldPreserveValue()
    {
        var attemptedValue = new
        {
            Name = "John",
            Age = 42
        };

        var failure = new ValidationFailure(
            "Customer",
            "invalid",
            "Customer is invalid.",
            attemptedValue);

        Assert.That(
            failure.AttemptedValue,
            Is.SameAs(attemptedValue));
    }

    /// <summary>
    /// Verifies the string representation generated by
    /// <see cref="ValidationFailure.ToString"/>.
    /// </summary>
    [Test]
    public void ToString_ShouldReturnPropertyNameAndMessage()
    {
        var failure = new ValidationFailure(
            "Name",
            "required",
            "Name is required.");

        Assert.That(
            failure.ToString(),
            Is.EqualTo("Name: Name is required."));
    }

    /// <summary>
    /// Verifies that the attempted value does not affect the string
    /// representation.
    /// </summary>
    [Test]
    public void ToString_ShouldNotIncludeAttemptedValue()
    {
        var failure = new ValidationFailure(
            "Name",
            "required",
            "Name is required.",
            "invalid-value");

        Assert.That(
            failure.ToString(),
            Is.EqualTo("Name: Name is required."));
    }

    /// <summary>
    /// Verifies record value equality when all values are equal.
    /// </summary>
    [Test]
    public void Equality_WithSameValues_ShouldBeEqual()
    {
        var first = new ValidationFailure(
            "Name",
            "required",
            "Name is required.",
            null,
            ValidationSeverity.Error);

        var second = new ValidationFailure(
            "Name",
            "required",
            "Name is required.",
            null,
            ValidationSeverity.Error);

        Assert.That(first, Is.EqualTo(second));
    }

    /// <summary>
    /// Verifies that different property names produce different
    /// validation failures.
    /// </summary>
    [Test]
    public void Equality_WithDifferentPropertyName_ShouldNotBeEqual()
    {
        var first = new ValidationFailure(
            "Name",
            "required",
            "Name is required.");

        var second = new ValidationFailure(
            "Email",
            "required",
            "Name is required.");

        Assert.That(first, Is.Not.EqualTo(second));
    }

    /// <summary>
    /// Verifies that different error codes produce different
    /// validation failures.
    /// </summary>
    [Test]
    public void Equality_WithDifferentErrorCode_ShouldNotBeEqual()
    {
        var first = new ValidationFailure(
            "Name",
            "required",
            "Name is required.");

        var second = new ValidationFailure(
            "Name",
            "invalid",
            "Name is required.");

        Assert.That(first, Is.Not.EqualTo(second));
    }

    /// <summary>
    /// Verifies that different messages produce different validation
    /// failures.
    /// </summary>
    [Test]
    public void Equality_WithDifferentMessage_ShouldNotBeEqual()
    {
        var first = new ValidationFailure(
            "Name",
            "required",
            "Name is required.");

        var second = new ValidationFailure(
            "Name",
            "required",
            "Another message.");

        Assert.That(first, Is.Not.EqualTo(second));
    }

    /// <summary>
    /// Verifies that different attempted values produce different
    /// validation failures.
    /// </summary>
    [Test]
    public void Equality_WithDifferentAttemptedValue_ShouldNotBeEqual()
    {
        var first = new ValidationFailure(
            "Name",
            "invalid",
            "Name is invalid.",
            "John");

        var second = new ValidationFailure(
            "Name",
            "invalid",
            "Name is invalid.",
            "Jane");

        Assert.That(first, Is.Not.EqualTo(second));
    }

    /// <summary>
    /// Verifies that different severities produce different validation
    /// failures.
    /// </summary>
    [Test]
    public void Equality_WithDifferentSeverity_ShouldNotBeEqual()
    {
        var first = new ValidationFailure(
            "Name",
            "warning",
            "Name should be reviewed.",
            "John",
            ValidationSeverity.Warning);

        var second = new ValidationFailure(
            "Name",
            "warning",
            "Name should be reviewed.",
            "John",
            ValidationSeverity.Error);

        Assert.That(first, Is.Not.EqualTo(second));
    }

    /// <summary>
    /// Verifies that a null property name is accepted because the record
    /// itself does not define constructor guards.
    /// </summary>
    [Test]
    public void Constructor_WithNullPropertyName_ShouldPreserveNull()
    {
        var failure = new ValidationFailure(
            null!,
            "required",
            "Value is required.");

        Assert.That(failure.PropertyName, Is.Null);
    }

    /// <summary>
    /// Verifies that a null error code is accepted because the record
    /// itself does not define constructor guards.
    /// </summary>
    [Test]
    public void Constructor_WithNullErrorCode_ShouldPreserveNull()
    {
        var failure = new ValidationFailure(
            "Name",
            null!,
            "Value is required.");

        Assert.That(failure.ErrorCode, Is.Null);
    }

    /// <summary>
    /// Verifies that a null message is accepted because the record itself
    /// does not define constructor guards.
    /// </summary>
    [Test]
    public void Constructor_WithNullMessage_ShouldPreserveNull()
    {
        var failure = new ValidationFailure(
            "Name",
            "required",
            null!);

        Assert.That(failure.Message, Is.Null);
    }
}
