<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <Deterministic>true</Deterministic>
        <AssemblyName>KUKULCAN.SharedKernel</AssemblyName>
        <RootNamespace>KUKULCAN.SharedKernel</RootNamespace>
        <PackageId>KUKULCAN.SharedKernel</PackageId>
        <Authors>Juan Manuel Pardo García</Authors>
        <Company>KUKULCAN Software Designer</Company>
        <Product>KUKULCAN Platform</Product>
        <Description>Shared kernel for the KUKULCAN platform.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Globalization\Formating\" />
    </ItemGroup>

</Project>
